### ISSUE TITLE
2. PCB는 어떤 것이고 무엇을 담고 있는가? 같은 프로세스 내의 쓰레드 사이와 다른 프로세스 쓰레드 사이의 컨텍스트 스위칭에는 어떤 차이가 있을까?

### ISSUE THREAD

**Issue by initmumu** [16th-Operating-System-study/operating-system#10]
# PCB (Process Control Block)란 무엇인가?

## 1. PCB의 정의
PCB (Process Control Block)는 운영체제가 각 프로세스의 상태를 관리하기 위해 사용하는 자료 구조이다. 운영체제는 이 PCB를 참조하여 프로세스를 스케줄링하고, 프로세스 간의 전환(Context Switching)을 수행한다. PCB는 각 프로세스에 대한 중요한 정보를 담고 있으며, 이러한 정보는 프로세스가 중단되었다가 다시 실행될 때 필요한 데이터를 포함한다.

## 2. PCB에 담기는 정보
PCB는 다음과 같은 주요 정보를 포함하고 있다:

- **프로세스 식별자 (PID, Process Identifier)**: 각 프로세스를 고유하게 식별하기 위한 ID.
- **프로세스 상태**: 프로세스가 현재 실행 중인지, 준비 상태인지, 대기 상태인지를 나타냄.
- **프로세스 카운터 (Program Counter)**: 프로세스가 다음에 실행할 명령어의 주소.
- **CPU 레지스터 값**: 프로세스가 사용하고 있는 CPU 레지스터들의 값.
- **메모리 관리 정보**: 페이지 테이블, 세그먼트 테이블 등 프로세스의 메모리 상태를 관리하는 정보.
- **입출력 상태 정보**: 프로세스가 사용 중인 입출력 장치나 파일에 대한 정보.
- **우선순위**: 프로세스의 우선순위 값으로, 스케줄링 시 중요한 요소.
- **계정 정보**: 프로세스 소유자와 관련된 사용자 정보.

운영체제는 PCB에 저장된 정보를 기반으로 프로세스를 제어하고, 각 프로세스가 올바르게 실행되도록 관리합니다.

# 같은 프로세스 내의 쓰레드 사이와 다른 프로세스 쓰레드 사이의 컨텍스트 스위칭 차이

## 1. 컨텍스트 스위칭이란?
컨텍스트 스위칭(Context Switching)은 CPU가 현재 실행 중인 프로세스나 쓰레드의 상태를 저장하고, 다음에 실행할 프로세스나 쓰레드의 상태를 로드하는 과정을 말합니다. 이를 통해 여러 프로세스나 쓰레드를 마치 동시에 실행하는 것처럼 보이게 만들 수 있다.

## 2. 같은 프로세스 내 쓰레드 사이의 컨텍스트 스위칭
같은 프로세스 내에서의 쓰레드 간 전환은 **경량 컨텍스트 스위칭**이라고도 불린다. 이 경우, 쓰레드가 같은 메모리 공간을 공유하므로 메모리 주소 공간이나 파일 디스크립터 등을 변경할 필요가 없다. 따라서, 컨텍스트 스위칭에 필요한 정보는 다음과 같다:

- **CPU 레지스터**: 쓰레드의 레지스터 값을 저장하고 로드.
- **프로그램 카운터**: 다음에 실행할 명령어의 위치를 저장.

같은 프로세스 내에서의 컨텍스트 스위칭은 메모리 및 리소스 관리 측면에서 가벼워, **속도가 빠르고 오버헤드가 적다**.

## 3. 다른 프로세스의 쓰레드 사이의 컨텍스트 스위칭
다른 프로세스의 쓰레드 간 전환은 **무거운 컨텍스트 스위칭**이다. 두 쓰레드는 서로 다른 프로세스에 속해 있으며, 이 경우 각각의 프로세스는 독립적인 메모리 공간과 리소스를 사용한다. 따라서 다음과 같은 더 많은 정보가 스위칭 시에 저장되고 복구되어야 한다:

- **메모리 주소 공간**: 각 프로세스는 독립된 메모리 공간을 가지므로, 주소 공간을 변경해야 한다.
- **페이지 테이블 정보**: 각 프로세스의 페이지 테이블을 다시 로드해야 한다.
- **파일 디스크립터 및 입출력 정보**: 다른 프로세스는 독립된 입출력 자원을 사용하므로, 이 정보도 스위칭 시 처리된다.

다른 프로세스 간의 컨텍스트 스위칭은 **상대적으로 시간이 많이 소요**되고, **오버헤드가 크다**.

## 4. 차이점 요약
| 항목 | 같은 프로세스 내 쓰레드 스위칭 | 다른 프로세스 쓰레드 스위칭 |
| --- | --- | --- |
| 메모리 공유 | 공유 | 독립적 |
| 컨텍스트 스위칭 속도 | 빠름 | 느림 |
| 오버헤드 | 낮음 | 높음 |
| 전환 시 필요한 정보 | CPU 레지스터, 프로그램 카운터 | 메모리 주소, 페이지 테이블, 파일 디스크립터 등 |

## 5. 결론
같은 프로세스 내의 쓰레드 간 컨텍스트 스위칭은 메모리와 리소스를 공유하므로 빠르고 효율적이다. 반면, 다른 프로세스 간의 쓰레드 전환은 독립적인 메모리 공간과 리소스를 변경해야 하므로 더 많은 오버헤드를 발생시킨다.

**Comment by PaikMyeongGyu** [comment]
PCB(Process Control Block)은 특정한 프로세스의 관리 정보를 포함하는 운영체제 커널의 자료구조이다. 각각의 프로세스들은 고유의 PCB를 가지고 있고 해당 PCB는 프로세스 내의 여러 쓰레드가 생길 때마다 각각의 쓰레드 정보를 담고 있는 TCB(Thread Control Block)에 대한 포인터를 가진다. 

해당 정보들은 커널의 메모리 영역에 올라가 있으며 PCB와 TCB에는 레지스터 정보, PC, 쓰레드 상태, stack 포인터 등의 여러 정보들을 가지며 PCB에는 프로세스 ID, 메모리 관리 정보, CPU 스케줄링 우선 순등 등의 정보가 있다.
 
![image](https://github.com/user-attachments/assets/efcf53bb-921c-435f-b14f-7a6cdacc6d47)

 같은 프로세스 내의 쓰레드와 다른 프로세스의 쓰레드 사이의 컨텍스트 스위칭 차이에 관해서 이해를 하기 위해서는 여러 가지 이해가 필요하다. 우선, 프로세스와 쓰레드의 메모리 차이이다. 프로세스는 개별적인 힙, 스택, 데이터, 코드 영역을 가진다. 쓰레드는 개별적인 스택 영역만을 가진다.

 쓰레드 단위로 같은 프로세스 내에서 컨텍스트 스위칭이 일어날 때에는 TCB에서 해당 쓰레드에 관한 스택 정보만을 교체해주면 된다. 이 작업은 상대적으로 PCB의 교체보다는 오버헤드가 작다.

 다른 프로세스 사이의 쓰레드가 교체될 때에는 스택 정보만을 갈아껴줘서 해결이 되지 않는다. 다른 프로세스의 쓰레드로 컨텍스트 스위칭할 때에는 기존 CPU에서 사용하고 있는 TLB와 MMU 정보를 저장하고 다른 프로세스에 있는 쓰레드로 컨텍스트 스위칭을 시킨다.  

다른 프로세스의 스레드로 위와 같은 추가적인 교체 비용이 물리적으로 드는 것도 있지만 가장 큰 문제는 기존에 프로그램을 돌리며 RAM에 저장한 메모리 영역의 캐시 정보를 모두 날려야 한다는 것이다. 프로세스의 데이터 영역은 모두 개별 데이터이다. 메모리 상으로 겹치는 곳이 없다고 보는 게 맞다. 그래서 cache hit이 극도로 순간적으로 낮아지는 현상이 발생해서 순간적 성능저하가 크게 일어난다.

※ 추가 정보: 위에 관한 이해를 위해선 Virtual Memory에 관한 이해가 필요한데, Virtual Memory에서 메모리 상에서 한정된 메모리를 제대로 사용하기 위해 Paging 기법을 사용하고 Paging 기법에서 Memory 영역에서 데이터를 가져오는 속도가 느리니 TLB(Translation Lookaside Buffer)와 MMU(Memory Manaagement Unit)이라는 추가적인 도구를 제공한다. MMU는 페이지 관리와 주소 변환 등의 기능을 하며 TLB는 페이지 테이블 접근 시간을 줄이기 위해서 메모리 보다 빠른 CPU 내에 존재하는 캐시이다.
