### ISSUE TITLE
7. Time interrupt는 무엇인가? 어떤 이유에서 자동으로 제어권을 OS로 옮겨야 하는가? 동시에 프로세스에서 요청을 하면 어떤 방식으로 처리할 수 있을까?

### ISSUE THREAD

**Issue by kimjm9841** [16th-Operating-System-study/operating-system#11]
### Time Interrupt

시분할(Time Sharing) 환경에서 특정 프로세스가 주어진 시간(Time Slice) 동안 작업을 완료하지 못했을 경우, 강제로 CPU 제어권을 뺏어 OS에게 넘겨주는 것이다.

OS는 자신이 임의로 CPU 제어권을 빼앗아올 수 없고 오직 인터럽트에 의해서 CPU 제어권을 얻을 수 있다. 즉, OS는 인터럽트에 의해 구동된다고 볼 수 있다.

따라서 이렇게 CPU 제어권을 자동으로 OS로 옮기지 않을 경우 프로세스가 자발적으로 CPU 제어권을 반납할 때까지 무한정 기다려야 한다. 즉, 특정 프로세스가 CPU 제어권을 독점할 수 있으며, 이로 인해 다른 프로세스가 기아 현상을 겪게 된다. 이를 막기 위해 일정 시간이 지날 때까지 프로세스가 CPU 제어권을 반납하지 않으면 강제로 빼앗는다.

### 인터럽트 처리 과정

1. 인터럽트 요청
    
    주어진 Time Slice가 모두 소요되었거나 I/O 장치에서 작업 완료를 알리기 위해 인터럽트가 발생한다.
    
2. 프로그램 실행 중단
    
    현재 수행 중이던 연산까지만 처리한 뒤 프로그램을 중단한다.
    
3. 현재 프로그램 상태 저장
    
    인터럽트 당한 시점의 PCB와 Program Counter 정보를 저장한다.
    
4. 인터럽트 벡터 확인
    
    CPU 제어권을 OS에게 넘겨 인터럽트 벡터를 확인한다. 인터럽트 벡터는 해당 인터럽트의 처리 루틴 주소를 가지고 있다.
    
5. 인터럽트 처리 루틴 실행
    
    인터럽트 벡터가 가리키는 주소로 이동해 인터럽트 처리 루틴을 실행한다.
    
6. 상태 복구
    
    인터럽트 처리 루틴이 끝나면 저장해뒀던 PCB와 Program Counter 정보를 다시 불러온다.
    
7. 중단된 프로그램 실행 재개
    
    중단되었던 프로그램을 다시 실행한다.
    

![image (2)](https://github.com/user-attachments/assets/cce7b78b-3c08-4dc3-9714-25bda04eac62)

또한 인터럽트 발생 시 항상 컨텍스트 스위칭이 일어나는 것은 아니다. 1번 같은 경우 인터럽트가 발생했지만 기존과 동일한 프로세스로 복귀하기 때문에 컨텍스트 스위칭이 발생하지 않는다. 물론 이 경우에도 CPU 수행 정보 등 컨텍스트의 일부 정보를 PCB에 저장해야 하지만 컨텍스트 스위칭보다 오버헤드가 훨씬 적다. 반면 Time Interrupt나 I/O 작업을 요청하는 System Call이 발생했을 경우 기존과 다른 프로세스로 복귀하게 되므로 컨텍스트 스위칭이 발생한다.

### 다중 인터럽트

동시에 여러 장치에서 인터럽트가 발생하거나, 이미 인터럽트 처리 루틴을 수행 중인데 인터럽트가 발생할 수 있다. 이를 다중 인터럽트라고 하며 현재 실행 중인 인터럽트 처리 루틴의 중단 가능 여부에 따라 다음과 같이 처리할 수 있다.

1. 중단할 수 없는 경우
    
    새로 들어오는 인터럽트 요청을 무시한다. 실시간 시스템이나 보안 관련 인터럽트가 이에 해당한다.
    
2. 중단할 수 있는 경우
    
    인터럽트의 우선순위를 따져서 처리한다. 현재 실행 중인 인터럽트가 새로운 인터럽트보다 우선순위가 높으면 새로 들어온 인터럽트를 미뤄뒀다가 나중에 처리한다. 반대로 우선순위가 낮으면 새로 들어온 인터럽트의 처리 루틴을 실행한다.
    

인터럽트 간의 우선순위는 다음과 같다. 일반적으로 소프트웨어 인터럽트보다 하드웨어 인터럽트가, 내부 인터럽트보다 외부 인터럽트가 우선순위가 높다.

> 전원 이상(Power fail) > 기계 착오(Machine Check) > 외부 신호(External) > 입출력(I/O) > 명령어 잘못 > 프로그램 검사(Program Check) > SVC(SuperVisor Call)
> 

---

**참고 자료**

- [[https://velog.io/@yuseogi0218/Interrupt-인터럽트](https://velog.io/@yuseogi0218/Interrupt-%EC%9D%B8%ED%84%B0%EB%9F%BD%ED%8A%B8)](https://velog.io/@yuseogi0218/Interrupt-%EC%9D%B8%ED%84%B0%EB%9F%BD%ED%8A%B8)
- [[https://velog.io/@chelsea/CPU의-인터럽트-사이클](https://velog.io/@chelsea/CPU%EC%9D%98-%EC%9D%B8%ED%84%B0%EB%9F%BD%ED%8A%B8-%EC%82%AC%EC%9D%B4%ED%81%B4)](https://velog.io/@chelsea/CPU%EC%9D%98-%EC%9D%B8%ED%84%B0%EB%9F%BD%ED%8A%B8-%EC%82%AC%EC%9D%B4%ED%81%B4)
- http://www.kocw.net/home/m/search/kemView.do?kemId=1046323

**Comment by PaikMyeongGyu** [comment]
처음 질문을 만들었을 때 명확하게 구분을 하지 않았다고 생각을 한다. 인터럽트는 이벤트에 대한 처리를 위해 하드웨어나 소프트웨어에서 신호를 보내는 것으로 프로세스가 현재 작업을 중지할 수 있게 요청을 한다 이는 두 가지로 구분을 할 수 있다.

 하드웨어 인터럽트(I/O Interrupt) : 입출력 장치(키보드, 마우스) 등에 의한 인터럽트 혹은 디스크에서 작업을 완료하고 데이터를 가져왔다는 의미로 동작하는 인터럽트이다. 프로세스의 상태 이미지에서 Wakeup 부분에 해당한다.

 소프트웨어 인터럽트(Timer Interrupt) : CPU 작업에서 OS가 기본적으로 설정한 타임 슬라이스를 모두 소진해 다른 프로세스로의 스위칭이 필요함을 의미한다. 혹은 시스템 콜이나 예외 처리(Non division by Zero) 같은 경우에 발생하는 에러이다. 프로세스 상태의 이미지에서 Interrupt 부분에 해당한다.
 
![image](https://github.com/user-attachments/assets/209d4f17-2b81-415f-a8d4-0e295ac6496f)

 어떤 이유에서 자동으로 제어권을 OS로 넘겨야하는가는 Interrupt가 왜 필요한 지에 대한 것으로 의미를 바꿔야 할 것 같다고 생각을 한다.

 Interrupt가 필요한 이유 첫 번째는 Time slice가 종료되는 Time runout 상황에 대해서 고민을 해보면 된다. 스케줄러에서 Time slice로 나누고 FIFO 등의 작업의 문제를 해결하기 위해 Round Robin 방식이 적용된 이유는 최대한 응답속도를 빠르게 하기 위함이었다. Interrupt는 특정 프로세스가 CPU를 독점해 불공정한 CPU 분배를 방지한다.

 두 번째 이유는 Wakeup 부분을 생각하면 된다. 프로세스는 CPU 자원만 사용하는 작업을 사용하는 게 아니라 DISK 자원도 같이 사용을 한다. 이 때 DISK 작업을 하는 동안 CPU가 쉬지만 동시에 CPU 자원을 점유하고 있는 것은 CPU 자원을 낭비하는 행위이다. 따라서, 자원의 낭비를 줄이기 위한 역할을 한다.

 스케줄러의 관점에서는 위의 두 가지 이유가 중요하다고 생각을 하고 그 외에는 특정 프로세스보다 위급한 작업을 가진 프로세스가 있을 때, 해당 프로세스로 제어권을 넘김으로써 해당 일을 우선 처리하는 역할을 한다고 생각을 한다.

사실 Interrupt라고 쓰고 Context Switching으로 작성을 해서 동시에 Interrupt가 발생한 상황에 관해 설명을 해보면 OS마다 다르고 모르겠다가 맞는 말이라고 생각을 한다. 각각의 처리방법은 다음과 같이 정리할 수 있다.

- Interrupt 중 가 장 빠른 것만 처리하고 그걸 처리하는 동안 다른 Interrupt에 관해서는 무시해버리는 방법이 있다.
- 우선 순위를 매겨서 우선 순위가 높은 걸 우선 처리하는 방법이 있다.
- Interrupt된 것에 대해 Queueing을 통해 요청에 대해 기록해두고 처리를 하는 방법이 있다.

또한, 이는 싱글 코어 환경과 멀티 코어 환경으로 구분에 대해서도 고민해보는 것이 맞다고 생각을 한다.

- 싱글 코어 환경에서의 동시에 여러 프로세스에서 Interrupt 요청이 들어오는 경우에는 동시에 실행할 방법이 없으므로 위의 방법대로 처리가 된다.
- 멀티 코어 환경에서는 동시에 여러 프로세스에서 Interrupt 요청이 들어올 때 둘 다 같이 처리를 할 수 있다. 그 경우에도 똑같이 처리를 할 수 있지만, 코어 개수만큼 동시에 실행이 가능하다. 또한, 최대한 cache 친화도를 높이는 방식으로 동작을 하는 방식이 추가된다는 점에 있어서 차이가 있다.

--> 보통 타임 아웃을 구현하는 방식에서 interrupt를 주로 사용을 하는데, 해당 Interrupt의 호출이 즉시 반영이 돼서 빠르게 종료하지 않는 이유 와도 이는 관련이 있다.
