### ISSUE TITLE
14. 비동기 요청은 무조건 동기 요청보다 빠른가?

### ISSUE THREAD

**Issue by initmumu** [16th-Operating-System-study/operating-system#28]
# 비동기 요청은 무조건 동기 요청보다 빠른가?
### 이에 답하기 위해선 더 자세한 가정이 필요
1. 수행하려는 작업이 I/O Bound 작업일 때
2. 싱글 코어 환경에서, CPU Bound 작업일 때

### 비동기 요청의 목적
비동기 요청은 크게 다음과 같은 목적을 위해 사용된다.
1. 동시성 향상
    - I/O Bound 같이 작업 대기 시간을 다른 작업을 할 때 사용함으로써, 많은 작업을 동시에 처리할 수 있음

2. 응답 시간 단축
    - 동기 요청에서는 앞선 작업이 끝나야 뒤의 작업이 시작됨
    - 즉, 늦게 들어오는 요청일 수록 응답 시간이 늘어지게 됨

> 길고 긴 I/O Time동안 CPU를 놀리지 않기 위해, 비동기 요청으로 효율성을 올릴 수 있다.

### 만약 CPU Bound Task라면?
CPU Bound Task는 애초에 CPU가 놀지 않는다. 앞서 말했듯이 비동기 요청은 CPU를 놀리지 않게 하기 위함이 주 목적이라고 볼 수 있는데, 애초에 **CPU가 놀지 않는 Task에서 비동기를 적용하는 것은 어불성설** 이다.<br>
오히려 수행속도가 저하될 수 있는데, **태스크를 쪼개고 병합하는 과정에서 오버헤드가 발생** 하기 때문이다.

**Comment by PaikMyeongGyu** [comment]
개인적으로 뭔가 이해가 덜 된 것 같아서 조금 더 고민해보겠음. 그래서 안 닫을게
