### ISSUE TITLE
13. CPU 캐시와 메모리에 관해서 설명해주세요.

### ISSUE THREAD

**Issue by initmumu** [16th-Operating-System-study/operating-system#29]
### L1, L2, L3 캐시의 차이점과 각 캐시의 동기화 시점
![](https://img2.quasarzone.com/editor/2021/01/16/c697dbaa10862212eba282c41d0e866c.png)
#### L1 캐시:

* **위치 및 크기**: 코어에 가장 가까이 존재하는 캐시로 각 코어마다 하나씩 존재
* **속도**: 가장 빠른 캐시로, CPU의 클럭 속도에 맞게 동작하여 지연 시간이 매우 짧음
* **구조**: 일반적으로 명령어 캐시와 데이터 캐시로 나뉘어져 있음

#### L2 캐시:

* **위치 및 크기**: 여러 코어가 공유하는 형태로 존재
* **속도**: L1 캐시보다 거리적으로 멀기 때문에, 접근 속도가 느리다.
* **구조**: 각 코어별로 독립적으로 존재하거나 공유될 수 있음

#### L3 캐시:

* **위치**: 모든 코어가 공유하는 형태로 존재하며
* **속도**: L2 캐시보다 지연 시간이 길지만 메인 메모리보다는 훨씬 빠름
* **구조**: 모든 코어가 접근할 수 있어 코어 간 데이터 공유에 효율적

#### 캐시 동기화(캐시 일관성) 시점:

* 데이터 수정 시: 한 코어에서 데이터를 수정하면, 다른 코어의 캐시에 해당 데이터가 존재할 수 있으므로 이를 무효화하거나 업데이트해야 함
* 캐시 미스(Cache Miss) 발생 시: 상위 캐시에 데이터가 없을 때 하위 캐시나 메인 메모리에서 데이터를 가져오며, 이 과정에서 동기화가 이루어짐
* 캐시 일관성 프로토콜 사용: MESI(Modified, Exclusive, Shared, Invalid)와 같은 프로토콜을 통해 캐시 간의 데이터 일관성을 유지

#### 공간 지역성(Spatial Locality):

* 정의: 특정 메모리 위치에 접근할 때 그 근처의 메모리 위치도 곧 접근할 가능성이 높은 특성
* 예시: 배열이나 연속된 메모리 구조를 순회할 때 발생
* 활용: 캐시는 이 특성을 이용하여 연속된 메모리 블록을 한 번에 로드

#### 시간 지역성(Temporal Locality):

* 정의: 최근에 접근한 메모리 위치가 가까운 미래에 다시 접근될 가능성이 높은 특성
* 예시: 반복문에서 동일한 변수나 데이터에 여러 번 접근할 때 나타남
* 활용: 캐시는 최근에 사용된 데이터를 유지하여 재사용 시 빠르게 접근할 수 있게 한다

#### 순차적 지역성(Sequential Locality):

* 정의: 메모리 접근이 연속적인 주소 순서로 이루어지는 특성
* 예시: 프로그램이 명령어를 순차적으로 실행하거나 데이터 배열을 순서대로 읽을 때 발생
* 관계: 공간 지역성의 한 형태로 볼 수 있습니다.

#### 캐시 라인(Cache Line):

* 정의: 캐시와 메모리 사이에서 데이터를 전송하는 기본 단위
* 크기: 일반적으로 64바이트이지만, 아키텍처에 따라 32바이트에서 128바이트까지 다양
* 동작 방식: 캐시는 캐시 라인 단위로 데이터를 저장하고 전송.
캐시 미스가 발생하면 필요한 데이터뿐만 아니라 그 주변의 데이터까지 포함된 캐시 라인을 가져옴
이는 공간 지역성을 활용하여 이후의 메모리 접근 시 캐시 히트율을 높이기 위함

#### 블록(Block):

* 정의: 캐시 라인과 동일한 의미로 사용되며, 캐시에서 데이터를 관리하는 최소 단위
* 역할: 캐시의 주소 매핑 및 교체 알고리즘에서 사용

**Comment by PaikMyeongGyu** [comment]
Write-back, Write-through, Allocate, no-allocate

**Comment by initmumu** [comment]
머지소트 지역성
