### ISSUE TITLE
6. fork() 시스템 콜을 통해 프로세스를 만들면 어떤 영역을 복사하게 되는가?(=자식 프로세스와 부모 프로세스 사이에 공유하는 건 무엇인가?)

### ISSUE THREAD

**Issue by Pearl-K** [16th-Operating-System-study/operating-system#7]
## 프로세스의 생성
부모 프로세스가 자식 프로세스를 생성할 때 복제 생성을 한다. (자식 프로세스는 부모 프로세스와 같은 나이를 가짐)
프로세스 자체가 프로세스를 생성할 수 없으므로 OS 에 System Call을 걸어 요청한다.

#### 이 System Call을 fork() 라고 한다.

***

### pid
- 부모 프로세스와 자식 프로세스는 pid를 통해 구분한다. (fork()의 return 값을 통한 구분)
- 부모 프로세스에서 return을 하면 자식 프로세스의 pid를 반환하기 때문에 양수를 반환
- 자식 프로세스에서는 자식이 없으므로 0을 반환
- pid의 구분을 통해 부모와 자식이 서로 다른 작업을 수행할 수 있다.

### 부모 프로세스
- fork() 호출 후 부모 프로세스는 자식 프로세스의 PID를 return
- 이때, 자식 프로세스의 PID는 항상 양수이다.
- 부모 프로세스에서 fork()가 성공하면 자식 프로세스의 고유한 PID가 return 되기 때문이다.

### 자식 프로세스:
- 자식 프로세스는 fork()가 성공하면 0을 반환 받는다.
- 자식 프로세스도 실행될 때 당연히 자신의 고유한 PID가 존재하지만, fork()가 반환하는 값은 0이다.
- 자식 프로세스가 자신의 PID가 필요한 경우, getpid()를 호출해서 자신의 PID를 얻을 수 있다.

### 오개념 주의! 
- 부모 프로세스와 자식 프로세스는 각자 본인의 고유 pid를 가지고 있으나 fork() 호출 후 return 할 때 돌려주는 pid가 본인의 pid가 아닌 자식의 pid임을 유의해야 한다.
- 자식 프로세스의 고유 pid가 0이라는 식의 설명을 주의 할 것!!

![fork_sys_call](https://github.com/user-attachments/assets/3c6d7905-4f04-4147-b6e5-2687c79cb82a)

<img src="https://github.com/user-attachments/assets/e842f623-6d7c-485f-8b97-f53b13fd75f1" alt="fork" style="width:300px; height:auto">

***

## fork() 시 복사되는 영역 (부모 프로세스에서 자식 프로세스로)
- Stack
- Heap
- Data
- PCB(Process Control Block)
   - fork() 시스템 콜을 호출하면 부모 프로세스의 PCB가 복제되어 자식 프로세스의 PCB가 만들어진다. 
   - 자식 프로세스는 부모의 메모리 상태를 복사하지만, PCB 내의 정보는 독립적으로 관리된다.
   - PCB에는 CPU에서 수행되던 레지스터의 값들이 저장되어 있고, Program Counter의 정보도 존재한다.
       -> Program Counter 값으로 인해 fork() 이후의 위치 이후부터 실행될 수 있는 것이다!
- 텍스트(text, 프로그램 코드)영역은 읽기 전용이므로 공유한다.

### 1. **가상 메모리와 페이지 테이블**:
   - **가상 메모리**
       - 프로세스마다 독립된 메모리 공간을 제공하는 방식 
       - 각 프로세스는 자신만의 고유한 메모리 주소 공간을 가지는 것처럼 동작한다. 
       - 하지만 실제로는 여러 프로세스가 물리 메모리를 공유하고 있다.
   - **페이지 테이블**
       - 가상 메모리와 실제 물리 메모리 사이를 연결해 주는 mapping 테이블
       - 운영 체제가 페이지 테이블을 통해 가상 주소를 물리 메모리의 적절한 주소로 변환하여 접근을 제어한다.

### 2. **fork()의 기본 동작**:
   - `fork()`는 부모 프로세스를 복제하여 자식 프로세스를 만드는데, 이때 자식 프로세스는 부모의 메모리 구조(코드, 데이터, 힙, 스택 영역)를 **복사**받는다.
   - 하지만 실제로 자식 프로세스가 부모의 메모리를 즉시 **물리적으로 복사**하지 않는다.
   - 자식 프로세스는 부모 프로세스와 동일한 **페이지 테이블을 복사**받아 동일한 물리 메모리 공간을 참조하는 형태가 된다.
   
### 3. **Copy-On-Write(COW) 정책**:
   - 물리 메모리 공유 상태에서 부모나 자식 프로세스가 메모리 데이터를 **읽기만 할 때**는 공유하며 성능 상의 이점을 누릴 수 있다.
   - 하지만 자식 또는 부모 프로세스가 해당 메모리 공간에 **쓰기 작업**을 시도하는 순간, 운영 체제는 **Copy-On-Write(COW)** 정책을 적용하여 **해당 페이지를 실제로 복사**한다. 
   - 즉, 쓰기 작업이 발생할 때에만 물리 메모리의 데이터를 복제하여 독립된 메모리 공간을 가지게 된다.

![fork_cow](https://github.com/user-attachments/assets/acf99798-d61d-4a19-8427-fd073e2e3a22)

### 4. **페이지 테이블의 역할**:
   -  페이지 테이블은 가상 메모리 주소와 물리 메모리 주소 간의 매핑 정보를 담고 있기 때문에, 처음에는 부모와 자식이 **동일한 물리 메모리**를 가리키게 된다.
   - 하지만 쓰기 작업이 발생하면, 운영 체제는 해당 페이지에 대해 **실제 물리 메모리 복사**를 수행하고, 복사된 메모리 주소를 자식 프로세스의 페이지 테이블에 반영한다.
   - 이 과정을 통해 부모와 자식은 서로 독립된 메모리 공간을 가지게 되고, 메모리 자원을 효율적으로 관리한다.
   - `Copy-On-Write` 정책을 적용하면 쓰기 작업이 발생할 때, 필요한 부분만 복사하므로 메모리와 CPU 리소스를 절약할 수 있다.

### **정리**:
- `fork()`는 자식 프로세스가 부모 프로세스의 페이지 테이블을 복사하여, 처음에는 부모와 자식이 동일한 물리 메모리 영역을 **공유**하게 된다.
- 물리 메모리의 실질적인 **복사**는 **쓰기 작업**이 발생할 때 일어나며, 이때 **Copy-On-Write(COW)** 정책이 적용되어 해당 메모리 페이지만 복사 된다.

***
ref.
- [fork_system](https://structuring.tistory.com/130)
- [process_system_call](https://rannnneey.tistory.com/entry/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%ED%94%84%EB%A1%9C%EC%84%B8%EC%8A%A4-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EC%BD%9Cfork-exec-wait-exit-IPCInter-Process-Commuication#google_vignette)
- [반효경 교수님 강의](http://www.kocw.net/home/search/kemView.do?kemId=1046323)
- [fork_n_COW](https://wslog.dev/fork-exec)
- [Copy_On_Write](https://cs-pub-ro.github.io/operating-systems/Lab/Compute/copy-on-write/)

**Comment by PaikMyeongGyu** [comment]
fork() 명령어를 통해서 자식 프로세스가 생성이 되면 자식 프로세스는 부모의 파일 디스크럽터를 상속을 받는다. 정확하게는 부모의 프로세스의 파일 디스크럽터 사본과 파일 포인터 위치를 받게 된다. 

사본을 받는다는 특성이 있기 때문에 둘의 파일 디스크럽터는 별 개로 동작하며, 부모가 닫았다고 혹은 새로 열었다고 자식에게도 그 영향이 가지 않는다. 반대도 똑같이 작용하기에 완전히 별도의 동작을 하게 된다. 이것은 또 다른 경쟁 자원이 탄생할 수 있음을 의미한다.

두 번째론 파일 디스크럽터가 복제되고 부차적으로 발생하는 문제이다. 파일 디스크럽터의 복제 자체는 용량이 크지 않기 때문에 큰 문제가 발생하지 않는다. 하지만, 메모리 페이지 공유에선 문제가 발생한다. 둘 사이의 메모리는 분리되지 않고 메모리 페이지를 공유한다. 그리고 공유한 메모리에서 수정(Write)이 일어날 때 해당 메모리 페이지를 복사를 해서 공유 영역이 아닌 개별의 영역으로 놓는데, 이 때 메모리 부하가 발생할 수 있다. 

위의 방식을 COW(Copy-on-Write)라고 하며 fork() 방식으로 백그라운드에서 요청을 처리하는 인메모리 방식의 DB에서는 위와 같은 문제로 메모리 사용량이 급격하게 증가하거나 메모리 페이지 복사 과정에서의 부하가 발생하는 문제가 발생할 수 있다.
 
![image](https://github.com/user-attachments/assets/9a119827-e7a5-4d42-9a35-3e37e6350f6e)
