### ISSUE TITLE
1. 프로세스의 상태(State)들에는 어떤 것이 있는가?

### ISSUE THREAD

**Issue by initmumu** [16th-Operating-System-study/operating-system#9]
# 프로세스 상태 (Process States)

운영체제에서 프로세스가 실행되는 동안 여러 상태를 거치게 됩니다. 프로세스 상태는 운영체제가 프로세스를 관리하는 중요한 요소 중 하나입니다. 일반적으로 다음과 같은 주요 프로세스 상태들이 있습니다.

![image](https://github.com/user-attachments/assets/f9f8daf2-a1e0-4e25-b274-422626cfd7da)

## 1. 생성 (New)
- **설명**: 프로세스가 막 생성된 상태입니다.
- **세부사항**: 프로세스가 실행되기 전에 초기화 작업을 수행하는 단계입니다.

## 2. 준비 (Ready)
- **설명**: 프로세스가 실행될 준비가 완료된 상태입니다.
- **세부사항**: CPU가 할당되기를 기다리는 상태로, 실행 대기 큐(Ready Queue)에 포함됩니다.

## 3. 실행 (Running)
- **설명**: 프로세스가 CPU를 할당받아 실행 중인 상태입니다.
- **세부사항**: 준비 상태에 있던 프로세스가 스케줄러에 의해 CPU를 할당받으면 실행 상태로 전환됩니다.

## 4. 대기 (Waiting) 또는 블록 (Blocked)
- **설명**: 프로세스가 특정 이벤트를 기다리고 있는 상태입니다.
- **세부사항**: 입출력 작업이나 특정 자원이 필요할 때 이 상태로 전환되며, 이벤트가 완료되면 다시 준비 상태로 전환됩니다.

## 5. 종료 (Terminated)
- **설명**: 프로세스가 실행을 모두 마치고 종료된 상태입니다.
- **세부사항**: 운영체제는 프로세스의 자원을 해제하고, 프로세스는 시스템에서 사라지게 됩니다.

---

### 추가 설명
운영체제에 따라 프로세스 상태는 더 세부적으로 나뉘기도 합니다. 예를 들어, 일부 시스템에서는 '일시 중단(Suspended)' 상태를 별도로 관리하기도 합니다. 하지만 위에서 설명한 5가지 상태는 대부분의 운영체제에서 공통적으로 사용되는 주요 상태입니다.

**Comment by PaikMyeongGyu** [comment]
프로세스는 다음과 같은 상태를 가진다.
-	New : 프로세스를 생성하기 위해 프로그램을 보조기억 장치에 넣은 상태이다.
-	Ready : 프로세스를 실행할 준비가 된 상태로 아직 OS의 스케줄링 정책에 의해 실행이 되지 않은 상태
-	Running : 프로세스가 스케줄링의 영향을 받아 실행 중인 상태
-	Waiting : 프로그램 실행 중 먼저 실행할 것이 있거나(Signal을 받아야 하는 경우), I/O 작업이 있어서 잠깐 프로세스가 멈춰진 상태
-	Terminated : 프로세스가 종료된 상태
 
![image](https://github.com/user-attachments/assets/066dab24-2eb0-4634-89c0-f00a348dc6d9)

1. Dispatch 과정 : ready 상태인 쓰레드가 OS 스케줄러의 영향을 받아서 CPU를 점유하여 running 상태로 전이되는 과정
2. Interrupt 과정 : running 중인 쓰레드가 본인에게 할당된 CPU 시간이 끝나 Interrupt가 발생해 trap 상태로 넘어가 제어권을 잃고 스케줄러가 선택한 다음 쓰레드가 running 상태가 되고 본인은 ready로 돌아가는 과정
3. Block 과정 : Lock이나 Disk I/O 같이 아직 본인에게 할당된 CPU 시간은 끝나지 않았지만, CPU를 점유할 필요가 없어 해당 작업이 끝날 때까지 CPU 제어권을 잃고 특정 신호를 대기하게 되는 과정
4. Wakeup 과정 : Block 과정에서 기다리는 작업이 끝나 신호를 받고 다시 CPU 제어권을 얻을 수 있는 장소로 돌아가는 과정

참고로 각각의 프로세스들이 담기는 큐에 프로세스들이 담겨 있다가 상황에 맞게 조절돼 이동한다.
